name: appinio_video_player
description: A custom video player that builds on top of the official video_player package by flutter and adds many functionalities.
version: 1.0.0
repository: https://gitlab.com/nimesh_bharadva/appinio_video_player_custome_package

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_video_player:
    git:
      url: https://github.com/iqonic-design/cached_video_player.git
      ref: 1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
